#!/bin/bash

MSG="$1"

if ! grep -qE "^(bfix|chor|conf|docs|feat|ptch|rfac): " "$MSG";then
    echo "Incorrect commit message."
    echo "Start your message with either"
    echo " - 'feat: '"
    echo " - 'ptch: '"
    echo " - 'bfix: '"
    echo " - 'rfac: '"
    echo " - 'chor: '"
    echo " - 'docs: '"
    echo " - 'conf: '"
    exit 1
fi
