version: '3'

services:
  selene:
    build:
      context: .
    container_name: selene
    ports:
      - "${HOST_PORT}:5000"
    volumes:
      - type: volume
        source: selene
        target: /selene/data

volumes:
  selene:
    name: "selene"
