name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Black and Pylint
      uses: ricardochaves/python-lint@v1.3.0
      with:
        python-root-list: .
        use-black: true
        use-pylint: true
        use-flake8: false
        use-isort: false
        use-mypy: false
        use-pycodestyle: false
