name: CI
on: [push, pull_request]
permissions:
  actions: write
  contents: read
jobs:
  prevent-duplicate:
    runs-on: ubuntu-latest
    outputs:
      is-duplicate: ${{ steps.detect-duplicate.outputs.should_skip }}
    steps:
      - name: Detect if workflow is running on the same code twice.
        id: detect-duplicate
        uses: fkirc/skip-duplicate-actions@v4.0.0
  check-formatting:
    runs-on: ubuntu-latest
    needs: prevent-duplicate
    if: needs.prevent-duplicate.outputs.is-duplicate != 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install and run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files
  run-tests:
    runs-on: ubuntu-latest
    needs: check-formatting
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Setup environment variables
        run: cp samples/.env .env
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest
